// RUN: p4mlir-translate --typeinference-only %s | FileCheck %s

// NOTE: Assertions have been autogenerated by utils/generate-test-checks.py

action bit5_and_int5_concat() {
    bit<5> lhs = 1;
    int<5> rhs = 2;

    bit<10> result = lhs ++ rhs;
}

// CHECK: #[[$ATTR_0:.+]] = #p4hir.int<1> : !b5i
// CHECK: #[[$ATTR_1:.+]] = #p4hir.int<2> : !i5i
// CHECK-LABEL:   p4hir.func action @bit5_and_int5_concat() {
// CHECK:           %[[VAL_0:.*]] = p4hir.const #[[$ATTR_0]]
// CHECK:           %[[VAL_1:.*]] = p4hir.cast(%[[VAL_0]] : !b5i) : !b5i
// CHECK:           %[[VAL_2:.*]] = p4hir.variable ["lhs", init] : <!b5i>
// CHECK:           p4hir.assign %[[VAL_1]], %[[VAL_2]] : <!b5i>
// CHECK:           %[[VAL_3:.*]] = p4hir.const #[[$ATTR_1]]
// CHECK:           %[[VAL_4:.*]] = p4hir.cast(%[[VAL_3]] : !i5i) : !i5i
// CHECK:           %[[VAL_5:.*]] = p4hir.variable ["rhs", init] : <!i5i>
// CHECK:           p4hir.assign %[[VAL_4]], %[[VAL_5]] : <!i5i>
// CHECK:           %[[VAL_6:.*]] = p4hir.read %[[VAL_2]] : <!b5i>
// CHECK:           %[[VAL_7:.*]] = p4hir.read %[[VAL_5]] : <!i5i>
// CHECK:           %[[VAL_8:.*]] = p4hir.concat(%[[VAL_6]] : !b5i, %[[VAL_7]] : !i5i) : !b10i
// CHECK:           %[[VAL_9:.*]] = p4hir.variable ["result", init] : <!b10i>
// CHECK:           p4hir.assign %[[VAL_8]], %[[VAL_9]] : <!b10i>
// CHECK:           p4hir.return
// CHECK:         }
